server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: amount-withdrawal-event
      properties:
        spring.json.trusted.packages: com.kamenskiy.io.core.events
      isolation-level: read_committed