server:
  port: 0
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.inflight.requests.per.connection: 5
        enable.idempotence: true

withdraw-money-topic: withdraw-money-topic
deposit-money-topic: deposit-money-topic
